### ISSUE TITLE
Registracijos bug'as

### ISSUE THREAD

**Issue by killeriax** [ZilvinasAbr/ImkStala#6]
Bandant registruoti naują restoraną su jau anksčiau naudotu el. paštu, restoranas vistiek sukuriamas duombazėje, nors ir registracija nesėkminga.

**Comment by ZilvinasAbr** [comment]
Ištaisytas

**Comment by ZilvinasAbr** [comment]
Nepavyko vis dėlto ištaisyti

**Comment by ZilvinasAbr** [comment]
Vėl "ištaisytas".
